export const GET_POSTS_URL = 'http://localhost:3000/api/get_posts/'
export const REFRESH_URL = 'http://localhost:3000/api/refresh'
export const LOG_OUT_URL = 'http://localhost:3000/api/logout'
export const LOG_IN_URL = 'http://localhost:3000/api/login'
export const REGISTRATION_URL = 'http://localhost:3000/api/registration'
export const NEW_POST_URL = 'http://localhost:3000/api/new_post'
export const CHANGE_POST_URL = 'http://localhost:3000/api/change_post'
export const DELETE_POST_URL = 'http://localhost:3000/api/del_post'